echo "Đang chuẩn bị quá trình update file lên github ....."
echo "cd /var/mobile/bonios.github.io"
echo "git add --all"
echo "git commit -m "Init commit""
echo "git push -u origin main"
echo "bonios"
echo "ghp_g6DFVfAwsTtqFdYRSYpQUghm0u5Tc20JlC6"
echo "xong!"
echo " Make by BoniOs!"
exit 0
